[package]
name = "sudoku"
version = "0.1.0"
authors = ["TonyMooori <tony.mooori@gmail.com>"]
edition = "2018"

[dependencies]
piston = "*"
pistoncore-glutin_window = "0.54.0"
piston2d-graphics = "0.30.0"
piston2d-opengl_graphics = "0.59.0"
rand = "0.6"